name: MacroPulse Daily Update

on:
  schedule:
    - cron: '0 21 * * *'  # 한국 시간 기준 매일 오전 6시 실행
  workflow_dispatch:      # 수동으로도 실행 가능하게 함

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install yfinance fredapi gspread google-auth pandas

      - name: Run script
        env:
          FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
          GCP_JSON_KEY: ${{ secrets.GCP_JSON_KEY }}
        run: python main.py
